# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]


release:
  footer: >-

    ---
    Copyright 2025 Ivan Vanderbyl. All rights reserved.
    Released under the [MIT License](https://opensource.org/licenses/MIT).

brews:
  - name: pdf-reader-mcp
    repository:
      owner: ivanvanderbyl
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    download_strategy: CurlDownloadStrategy
    homepage: "https://github.com/ivanvanderbyl/pdf-reader-mcp"
    description: "A Model Context Protocol (MCP) server for reading and analyzing PDF documents"
    license: "MIT"
    test: |
      system "#{bin}/pdf-reader-mcp --help"
    install: |
      bin.install "pdf-reader-mcp"
    commit_author:
      name: "Ivan Vanderbyl"
    directory: "Formula"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
